export interface JobItem {
  id: string;
  jobName: string;
  isNew: boolean;
  customerName: string;
  createTime: string;
  workLocation: string;
  isManager: string;
  deliveryManager: string;
  deliveryConsultant: string;
  jobStatus: string;
  jobDescription?: string;
  children?: JobItem[];
}

export const mockJobList: JobItem[] = [
  {
    id: '1',
    jobName: '淘宝闪购-保险业务总监-杭州',
    isNew: true,
    customerName: '阿里巴巴（中国）网络技术...',
    createTime: '2026.08.06 14:20',
    workLocation: '浙江省-杭州市、上...',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '2',
    jobName: '大模型算法工程师',
    isNew: true,
    customerName: '北京国科融机智能科技有限...',
    createTime: '2026.08.06 14:20',
    workLocation: '北京-北京市',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '3',
    jobName: '总经理',
    isNew: false,
    customerName: '北京国科融机智能科技有限...',
    createTime: '2026.08.06 14:20',
    workLocation: '北京-北京市',
    isManager: '是',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '4',
    jobName: '具身算法工程师（VLA）(J14298)',
    isNew: true,
    customerName: '云鲸智能创新（深圳）有限...',
    createTime: '2026.08.06 14:20',
    workLocation: '广东省-深圳市',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '5',
    jobName: '具身算法工程师(VLA方向)',
    isNew: true,
    customerName: '云鲸智能创新（深圳）有限...',
    createTime: '2026.08.06 14:20',
    workLocation: '广东省-深圳市',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '6',
    jobName: '运控负责人',
    isNew: true,
    customerName: '斜跃智能',
    createTime: '2026.08.06 14:20',
    workLocation: '浙江省-杭州市',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '7',
    jobName: '具身机器人导航与运动规划算法工程师',
    isNew: true,
    customerName: '北京汉朔科技有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '北京-北京市',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '8',
    jobName: '具身机器人电气与控制系统工程师',
    isNew: true,
    customerName: '北京汉朔科技有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '北京-北京市',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '9',
    jobName: '具身机器人机械工程师',
    isNew: true,
    customerName: '北京汉朔科技有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '北京-北京市',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '10',
    jobName: '智舱中间件开发工程师-主动降噪算法团队负...',
    isNew: true,
    customerName: '北汽重型汽车有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '北京-北京市',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '11',
    jobName: '淘宝闪购-C端Agent - AI Infra专家-上海',
    isNew: true,
    customerName: '阿里巴巴（中国）网络技术...',
    createTime: '2026.08.05 11:15',
    workLocation: '上海-上海市',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '12',
    jobName: '阿里云智能-应用研发专家（金融智能体）-...',
    isNew: true,
    customerName: '阿里云计算有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '北京-北京市、浙江...',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '13',
    jobName: '阿里云智能-智能体评测与优化专家（金融）-...',
    isNew: true,
    customerName: '阿里云计算有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '北京-北京市、浙江...',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '14',
    jobName: '蚂蚁集团-Agent工程师-数字医疗健康险',
    isNew: true,
    customerName: '蚂蚁科技集团股份有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '上海-上海市、浙江...',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '15',
    jobName: '蚂蚁集团-测试开发工程师（AI Native）-财富',
    isNew: true,
    customerName: '蚂蚁科技集团股份有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '上海-上海市、北京...',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '16',
    jobName: 'Java开发工程师',
    isNew: true,
    customerName: '腾讯科技（深圳）有限公司',
    createTime: '2026.08.07 09:30',
    workLocation: '深圳',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '17',
    jobName: '产品经理',
    isNew: false,
    customerName: '字节跳动有限公司',
    createTime: '2026.08.07 09:30',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '18',
    jobName: 'UI设计师',
    isNew: true,
    customerName: '美团',
    createTime: '2026.08.07 09:30',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '19',
    jobName: '数据分析师',
    isNew: false,
    customerName: '京东集团',
    createTime: '2026.08.06 14:20',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '20',
    jobName: '前端开发工程师',
    isNew: true,
    customerName: '拼多多',
    createTime: '2026.08.06 14:20',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '21',
    jobName: '后端开发工程师',
    isNew: true,
    customerName: '百度在线网络技术（北京）有限公司',
    createTime: '2026.08.06 14:20',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '22',
    jobName: '运维工程师',
    isNew: false,
    customerName: '快手科技',
    createTime: '2026.08.05 11:15',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '23',
    jobName: '测试工程师',
    isNew: true,
    customerName: '滴滴出行科技有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已关闭',
  },
  {
    id: '24',
    jobName: '架构师',
    isNew: false,
    customerName: '小米集团',
    createTime: '2026.08.04 16:45',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '25',
    jobName: '技术总监',
    isNew: true,
    customerName: '华为技术有限公司',
    createTime: '2026.08.04 16:45',
    workLocation: '深圳',
    isManager: '是',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '26',
    jobName: '运营经理',
    isNew: false,
    customerName: 'OPPO广东移动通信有限公司',
    createTime: '2026.08.04 16:45',
    workLocation: '深圳',
    isManager: '是',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '27',
    jobName: '市场经理',
    isNew: true,
    customerName: '维沃移动通信有限公司（vivo）',
    createTime: '2026.08.04 16:45',
    workLocation: '深圳',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '28',
    jobName: '销售总监',
    isNew: false,
    customerName: '网易（杭州）网络有限公司',
    createTime: '2026.08.03 10:00',
    workLocation: '杭州',
    isManager: '是',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '29',
    jobName: 'HRBP',
    isNew: true,
    customerName: '搜狐公司',
    createTime: '2026.08.03 10:00',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '30',
    jobName: '财务经理',
    isNew: false,
    customerName: '新浪公司',
    createTime: '2026.08.03 10:00',
    workLocation: '北京',
    isManager: '是',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '31',
    jobName: '法务经理',
    isNew: true,
    customerName: '携程集团',
    createTime: '2026.08.03 10:00',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '32',
    jobName: '品牌经理',
    isNew: true,
    customerName: '哔哩哔哩股份有限公司',
    createTime: '2026.08.02 15:30',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '33',
    jobName: '供应链经理',
    isNew: false,
    customerName: '知乎',
    createTime: '2026.08.02 15:30',
    workLocation: '北京',
    isManager: '是',
    jobDescription: '',
    jobStatus: '已关闭',
  },
  {
    id: '34',
    jobName: '采购经理',
    isNew: true,
    customerName: '小红书科技有限公司',
    createTime: '2026.08.02 15:30',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '35',
    jobName: '项目经理',
    isNew: true,
    customerName: '得物App',
    createTime: '2026.08.02 15:30',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '36',
    jobName: 'Scrum Master',
    isNew: false,
    customerName: '蔚来汽车',
    createTime: '2026.08.01 08:45',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '37',
    jobName: 'DevOps工程师',
    isNew: true,
    customerName: '理想汽车',
    createTime: '2026.08.01 08:45',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '38',
    jobName: '全栈工程师',
    isNew: true,
    customerName: '小鹏汽车',
    createTime: '2026.08.01 08:45',
    workLocation: '广州',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '39',
    jobName: '算法工程师',
    isNew: false,
    customerName: '比亚迪股份有限公司',
    createTime: '2026.08.07 09:30',
    workLocation: '深圳',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '40',
    jobName: '数据科学家',
    isNew: true,
    customerName: '宁德时代新能源科技股份有限公司',
    createTime: '2026.08.07 09:30',
    workLocation: '宁德',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '41',
    jobName: '机器学习工程师',
    isNew: true,
    customerName: '隆基绿能科技股份有限公司',
    createTime: '2026.08.06 14:20',
    workLocation: '西安',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '42',
    jobName: 'NLP工程师',
    isNew: false,
    customerName: '药明康德',
    createTime: '2026.08.06 14:20',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '43',
    jobName: '计算机视觉工程师',
    isNew: true,
    customerName: '深圳迈瑞生物医疗电子股份有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '深圳',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '44',
    jobName: '推荐算法工程师',
    isNew: true,
    customerName: '江苏恒瑞医药股份有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '连云港',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '45',
    jobName: '搜索算法工程师',
    isNew: false,
    customerName: '爱尔眼科医院集团股份有限公司',
    createTime: '2026.08.04 16:45',
    workLocation: '长沙',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '46',
    jobName: '广告算法工程师',
    isNew: true,
    customerName: '中国平安保险（集团）股份有限公司',
    createTime: '2026.08.04 16:45',
    workLocation: '深圳',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '47',
    jobName: '风控算法工程师',
    isNew: true,
    customerName: '招商银行股份有限公司',
    createTime: '2026.08.04 16:45',
    workLocation: '深圳',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '48',
    jobName: '量化交易员',
    isNew: false,
    customerName: '中信证券股份有限公司',
    createTime: '2026.08.03 10:00',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已关闭',
  },
  {
    id: '49',
    jobName: '区块链工程师',
    isNew: true,
    customerName: '中国国际金融股份有限公司',
    createTime: '2026.08.03 10:00',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '50',
    jobName: '游戏开发工程师',
    isNew: true,
    customerName: '华泰证券股份有限公司',
    createTime: '2026.08.03 10:00',
    workLocation: '南京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已关闭',
  },
  {
    id: '51',
    jobName: '嵌入式工程师',
    isNew: false,
    customerName: '国泰君安证券股份有限公司',
    createTime: '2026.08.02 15:30',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '52',
    jobName: '硬件工程师',
    isNew: true,
    customerName: '广发证券股份有限公司',
    createTime: '2026.08.02 15:30',
    workLocation: '广州',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '53',
    jobName: '芯片设计工程师',
    isNew: true,
    customerName: '海通证券股份有限公司',
    createTime: '2026.08.01 08:45',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '54',
    jobName: '自动驾驶工程师',
    isNew: false,
    customerName: '申万宏源证券有限公司',
    createTime: '2026.08.01 08:45',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '55',
    jobName: '车联网工程师',
    isNew: true,
    customerName: '国信证券股份有限公司',
    createTime: '2026.08.07 09:30',
    workLocation: '深圳',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已关闭',
  },
  {
    id: '56',
    jobName: '智能制造工程师',
    isNew: true,
    customerName: '东方财富信息股份有限公司',
    createTime: '2026.08.07 09:30',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '57',
    jobName: '工业互联网工程师',
    isNew: false,
    customerName: '浙江核新同花顺网络信息股份有限公司',
    createTime: '2026.08.06 14:20',
    workLocation: '杭州',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已暂停',
  },
  {
    id: '58',
    jobName: '云计算工程师',
    isNew: true,
    customerName: '上海大智慧股份有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '上海',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '59',
    jobName: '大数据工程师',
    isNew: true,
    customerName: '恒生电子股份有限公司',
    createTime: '2026.08.05 11:15',
    workLocation: '杭州',
    isManager: '否',
    jobDescription: '',
    jobStatus: '进行中',
  },
  {
    id: '60',
    jobName: '网络安全工程师',
    isNew: false,
    customerName: '用友网络科技股份有限公司',
    createTime: '2026.08.04 16:45',
    workLocation: '北京',
    isManager: '否',
    jobDescription: '',
    jobStatus: '已关闭',
  },
].map((item, index) => {
  const namePool = [
    '张经理', '李顾问', '王芳', '刘洋', '陈静', '杨超', '赵敏', '周伟', '吴磊', '徐丽',
    '孙强', '马丽', '朱磊', '胡敏', '何伟', '郭丽', '林涛', '黄杰', '罗敏', '梁伟',
  ];
  const companyPool = [
    '星辰科技有限公司', '蓝海网络有限公司', '云帆信息科技有限公司', '智创未来科技有限公司',
    '天擎数据有限公司', '锐达智能科技有限公司', '鸿图软件有限公司', '盈科互联科技有限公司',
    '远航科技有限公司', '鼎盛网络科技有限公司', '博彦信息技术有限公司', '汇聚科技有限公司',
    '腾云科技有限公司', '智联网络有限公司', '光辉科技有限公司', '华创信息科技有限公司',
    '迅达网络科技有限公司', '卓越软件有限公司', '银河科技有限公司', '瑞思互联有限公司',
  ];
  const jobNamePool = [
    '保险业务总监', '大模型算法工程师', '总经理', '具身算法工程师', '运控负责人',
    '机器人导航算法工程师', '电气控制系统工程师', '机械工程师', '中间件开发工程师',
    'AI Infra专家', '应用研发专家', '智能体评测专家', 'Agent工程师', '测试开发工程师',
    'Java开发工程师', '产品经理', 'UI设计师', '数据分析师', '前端开发工程师',
    '后端开发工程师', '运维工程师', '测试工程师', '架构师', '技术总监',
    '运营经理', '市场经理', '销售总监', 'HRBP', '财务经理',
    '法务经理', '品牌经理', '供应链经理', '采购经理', '项目经理',
    'Scrum Master', 'DevOps工程师', '全栈工程师', '算法工程师', '数据科学家',
    '机器学习工程师', 'NLP工程师', '计算机视觉工程师', '推荐算法工程师', '搜索算法工程师',
    '广告算法工程师', '风控算法工程师', '量化交易员', '区块链工程师', '游戏开发工程师',
    '嵌入式工程师', '硬件工程师', '芯片设计工程师', '自动驾驶工程师', '车联网工程师',
    '智能制造工程师', '工业互联网工程师', '云计算工程师', '大数据工程师', '网络安全工程师',
  ];
  const locationPool = [
    '北京市', '上海市', '广东省-深圳市', '浙江省-杭州市', '江苏省-南京市',
    '四川省-成都市', '湖北省-武汉市', '陕西省-西安市', '湖南省-长沙市', '河南省-郑州市',
    '重庆市', '天津市', '广东省-广州市', '浙江省-宁波市', '江苏省-苏州市',
    '山东省-青岛市', '辽宁省-大连市', '福建省-厦门市', '安徽省-合肥市', '江西省-南昌市',
    '河北省-石家庄市', '山西省-太原市', '吉林省-长春市', '黑龙江省-哈尔滨市', '云南省-昆明市',
    '贵州省-贵阳市', '海南省-海口市', '甘肃省-兰州市', '青海省-西宁市', '台湾省-台北市',
    '内蒙古自治区-呼和浩特市', '广西壮族自治区-南宁市', '西藏自治区-拉萨市', '宁夏回族自治区-银川市', '新疆维吾尔自治区-乌鲁木齐市',
  ];
  return {
    ...item,
    jobName: jobNamePool[index % jobNamePool.length],
    customerName: companyPool[index % companyPool.length],
    workLocation: locationPool[index % locationPool.length],
    deliveryManager: namePool[index % namePool.length],
    deliveryConsultant: namePool[(index + 1) % namePool.length],
  };
});

export const companyLevelColors: Record<string, string> = {
  '大厂': 'blue',
  '中厂': 'cyan',
  '小厂': 'default',
};

export const priorityColors: Record<string, string> = {
  '一级': 'red',
  '二级': 'orange',
  '三级': 'green',
};
